/**
 * 상세페이지 완성형 템플릿 레시피
 * 각 레시피 = 이름 + 스타일 설명 + 팔레트 + 카테고리 + Unsplash 이미지 + 섹션 구성
 * 이미지: Unsplash (상업적 무료)
 */

const U = (id, w = 300, h = 400) => `https://images.unsplash.com/${id}?w=${w}&h=${h}&fit=crop&q=80`;

export const TEMPLATE_RECIPES = [
  {
    id: "minimal_white",
    name: "미니멀 화이트",
    desc: "깔끔한 화이트 배경, 여백 중심 디자인",
    tags: ["living", "tech", "beauty"],
    palette: { main: "#1a1a2e", gradient: "#555", light_bg: "#ffffff", dark_bg: "#1a1a2e" },
    sections: ["hero", "features", "point", "stats_highlight", "review", "cta"],
    heroLayout: "centered_text",
    preview: {
      heroImg: U("photo-1505740420928-5e560c06d30e", 280, 160),
      accentColor: "#1a1a2e",
      heroBg: "#fff",
      cardBg: "#f8f8f8",
      statsBg: "#1a1a2e",
    },
  },
  {
    id: "natural_cream",
    name: "내추럴 크림",
    desc: "따뜻한 크림톤, 자연스러운 고급 감성",
    tags: ["food", "farm", "health", "beauty"],
    palette: { main: "#8B7355", gradient: "#A69279", light_bg: "#f9f6f2", dark_bg: "#2c2c2c" },
    sections: ["hero", "features", "point", "point", "stats_highlight", "review", "cta"],
    heroLayout: "full_image",
    preview: {
      heroImg: U("photo-1504674900247-0877df9cc836", 280, 160),
      accentColor: "#8B7355",
      heroBg: "#f9f6f2",
      cardBg: "#f5f0e8",
      statsBg: "#2c2c2c",
    },
  },
  {
    id: "luxury_dark",
    name: "럭셔리 다크",
    desc: "다크 배경에 골드 포인트, 프리미엄 무드",
    tags: ["beauty", "fashion", "tech"],
    palette: { main: "#c9a961", gradient: "#b8956a", light_bg: "#f5f5f5", dark_bg: "#1a1a2e" },
    sections: ["hero", "pain_points", "features", "point", "comparison", "guarantee", "cta"],
    heroLayout: "color_overlay",
    preview: {
      heroImg: U("photo-1523293182086-7651a899d37f", 280, 160),
      accentColor: "#c9a961",
      heroBg: "#1a1a2e",
      cardBg: "#111",
      statsBg: "#0a0a16",
    },
  },
  {
    id: "soft_pink",
    name: "소프트 핑크",
    desc: "부드러운 핑크/라벤더, 여성 감성 디자인",
    tags: ["beauty", "fashion", "kids"],
    palette: { main: "#d4829c", gradient: "#c4a0d8", light_bg: "#fef7f7", dark_bg: "#2c2035" },
    sections: ["hero", "features", "point", "review", "stats_highlight", "cta"],
    heroLayout: "centered_text",
    preview: {
      heroImg: U("photo-1596462502278-27bfdc403348", 280, 160),
      accentColor: "#d4829c",
      heroBg: "#fef7f7",
      cardBg: "#fdf0f3",
      statsBg: "#2c2035",
    },
  },
  {
    id: "bold_red",
    name: "볼드 임팩트",
    desc: "강렬한 레드 포인트, 시선을 사로잡는 디자인",
    tags: ["food", "tech", "living"],
    palette: { main: "#ef4444", gradient: "#f59e0b", light_bg: "#fff", dark_bg: "#0a0a0a" },
    sections: ["hero", "pain_points", "features", "comparison", "stats_highlight", "cta"],
    heroLayout: "full_image",
    preview: {
      heroImg: U("photo-1546069901-ba9599a7e63c", 280, 160),
      accentColor: "#ef4444",
      heroBg: "#0a0a0a",
      cardBg: "#fff",
      statsBg: "#0a0a0a",
    },
  },
  {
    id: "fresh_green",
    name: "프레시 그린",
    desc: "친환경/유기농 컨셉, 건강한 그린톤",
    tags: ["farm", "food", "health", "pet"],
    palette: { main: "#2d6a4f", gradient: "#52b788", light_bg: "#f0fff4", dark_bg: "#1a2e1a" },
    sections: ["hero", "features", "point", "stats_highlight", "cert", "review", "cta"],
    heroLayout: "centered_text",
    preview: {
      heroImg: U("photo-1542838132-92c53300491e", 280, 160),
      accentColor: "#2d6a4f",
      heroBg: "#f0fff4",
      cardBg: "#e8f5e9",
      statsBg: "#1a2e1a",
    },
  },
  {
    id: "tech_blue",
    name: "테크 블루",
    desc: "신뢰감 있는 블루, IT/전자제품에 적합",
    tags: ["tech", "education", "living"],
    palette: { main: "#2563eb", gradient: "#3b82f6", light_bg: "#eff6ff", dark_bg: "#0f172a" },
    sections: ["hero", "features", "comparison", "point", "stats_highlight", "faq", "cta"],
    heroLayout: "color_overlay",
    preview: {
      heroImg: U("photo-1519389950473-47ba0277781c", 280, 160),
      accentColor: "#2563eb",
      heroBg: "#0f172a",
      cardBg: "#eff6ff",
      statsBg: "#0f172a",
    },
  },
  {
    id: "warm_orange",
    name: "따뜻한 오렌지",
    desc: "활기차고 친근한 오렌지톤, 식품/키즈",
    tags: ["food", "kids", "education"],
    palette: { main: "#ea580c", gradient: "#f59e0b", light_bg: "#fff7ed", dark_bg: "#431407" },
    sections: ["hero", "pain_points", "features", "point", "review", "stats_highlight", "cta"],
    heroLayout: "full_image",
    preview: {
      heroImg: U("photo-1565299624946-b28f40a0ae38", 280, 160),
      accentColor: "#ea580c",
      heroBg: "#fff7ed",
      cardBg: "#fef3c7",
      statsBg: "#431407",
    },
  },
  {
    id: "classic_serif",
    name: "클래식 세리프",
    desc: "세리프 폰트와 여백, 전통적 고급 디자인",
    tags: ["food", "beauty", "fashion"],
    palette: { main: "#44403c", gradient: "#78716c", light_bg: "#fafaf9", dark_bg: "#292524" },
    sections: ["hero", "point", "features", "stats_highlight", "review", "guarantee", "cta"],
    heroLayout: "centered_text",
    preview: {
      heroImg: U("photo-1559056199-641a0ac8b55e", 280, 160),
      accentColor: "#44403c",
      heroBg: "#fafaf9",
      cardBg: "#f5f5f4",
      statsBg: "#292524",
    },
  },
  {
    id: "vivid_purple",
    name: "비비드 퍼플",
    desc: "메이킷 시그니처 퍼플, 트렌디한 감성",
    tags: ["beauty", "fashion", "tech", "education"],
    palette: { main: "#7c6aff", gradient: "#a78bfa", light_bg: "#faf5ff", dark_bg: "#1e1b4b" },
    sections: ["hero", "features", "point", "comparison", "stats_highlight", "review", "cta"],
    heroLayout: "color_overlay",
    preview: {
      heroImg: U("photo-1522335789203-aabd1fc54bc9", 280, 160),
      accentColor: "#7c6aff",
      heroBg: "#1e1b4b",
      cardBg: "#faf5ff",
      statsBg: "#1e1b4b",
    },
  },
  {
    id: "cool_gray",
    name: "쿨 그레이",
    desc: "모노톤 그레이, 세련된 미니멀 디자인",
    tags: ["tech", "living", "fashion"],
    palette: { main: "#374151", gradient: "#6b7280", light_bg: "#f3f4f6", dark_bg: "#111827" },
    sections: ["hero", "features", "point", "stats_highlight", "comparison", "cta"],
    heroLayout: "full_image",
    preview: {
      heroImg: U("photo-1493723843671-1d655e66ac1c", 280, 160),
      accentColor: "#374151",
      heroBg: "#f3f4f6",
      cardBg: "#e5e7eb",
      statsBg: "#111827",
    },
  },
  {
    id: "rose_gold",
    name: "로즈 골드",
    desc: "로즈골드 + 화이트, 여성 타겟 프리미엄",
    tags: ["beauty", "fashion", "health"],
    palette: { main: "#b76e79", gradient: "#d4a0a7", light_bg: "#fdf2f4", dark_bg: "#3d1f25" },
    sections: ["hero", "features", "point", "review", "stats_highlight", "guarantee", "cta"],
    heroLayout: "centered_text",
    preview: {
      heroImg: U("photo-1571781926291-c477ebfd024b", 280, 160),
      accentColor: "#b76e79",
      heroBg: "#fdf2f4",
      cardBg: "#fce7eb",
      statsBg: "#3d1f25",
    },
  },
];

/** 카테고리 키 → 추천 템플릿 우선 정렬 */
export function getRecommendedTemplates(catKey) {
  if (!catKey) return TEMPLATE_RECIPES;
  return [
    ...TEMPLATE_RECIPES.filter(t => t.tags.includes(catKey)),
    ...TEMPLATE_RECIPES.filter(t => !t.tags.includes(catKey)),
  ];
}
