export const editorStyles = {
  overlay: { position: "fixed", inset: 0, zIndex: 9999, background: "rgba(0,0,0,0.55)", backdropFilter: "blur(4px)", display: "flex", alignItems: "center", justifyContent: "center", padding: 12 },
  modal: { width: "100%", maxWidth: 1400, height: "95vh", background: "#fff", borderRadius: 16, display: "flex", overflow: "hidden", boxShadow: "0 8px 60px rgba(0,0,0,0.25)" },
  canvasArea: { display: "flex", flexDirection: "column", background: "#f0f0f5", padding: 0, overflow: "hidden" },
  slideNav: { display: "flex", alignItems: "center", gap: 10, padding: "10px 16px", background: "#fff", borderBottom: "1px solid rgba(0,0,0,0.08)" },
  navBtn: { background: "none", border: "1px solid rgba(0,0,0,0.12)", borderRadius: 6, padding: "4px 8px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" },
  templateStrip: { display: "flex", alignItems: "center", gap: 4, padding: "6px 12px", background: "#fff", borderBottom: "1px solid rgba(0,0,0,0.06)", overflowX: "auto", whiteSpace: "nowrap", scrollbarWidth: "thin" },
  templateChip: { display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 3, borderRadius: "50%", border: "1px solid transparent", background: "transparent", cursor: "pointer", transition: "all 0.15s", flexShrink: 0 },
  layoutPicker: { position: "absolute", bottom: "110%", left: "50%", transform: "translateX(-50%)", background: "#fff", borderRadius: 12, padding: 10, boxShadow: "0 4px 24px rgba(0,0,0,0.18)", border: "1px solid rgba(0,0,0,0.08)", display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 6, zIndex: 100, minWidth: 220 },
  layoutOption: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 2, padding: "8px 4px", borderRadius: 8, border: "1px solid rgba(0,0,0,0.08)", background: "#f9f9fb", cursor: "pointer", transition: "all 0.15s", minWidth: 48 },
  canvasContainer: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", overflow: "hidden", padding: 8, background: "#e8e8ee" },
  toolbar: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 6, padding: "8px 12px", background: "#fff", borderTop: "1px solid rgba(0,0,0,0.08)" },
  quickActions: { display: "flex", flexWrap: "wrap", gap: 6, padding: "6px 12px 10px", background: "#fff", borderTop: "1px solid rgba(0,0,0,0.04)" },
  panel: { display: "flex", flexDirection: "column", background: "#fafafe", borderLeft: "1px solid rgba(0,0,0,0.08)", overflowY: "auto", padding: "0 0 16px" },
  panelTitle: { fontSize: 15, fontWeight: 700, padding: "14px 18px", borderBottom: "1px solid rgba(0,0,0,0.06)", position: "sticky", top: 0, background: "#fafafe", zIndex: 2 },
  section: { padding: "14px 18px", borderBottom: "1px solid rgba(0,0,0,0.05)" },
  sectionLabel: { fontSize: 13, fontWeight: 700, marginBottom: 10, color: "#333" },
  label: { display: "block", fontSize: 12, fontWeight: 600, color: "#666", marginTop: 8, marginBottom: 4 },
  select: { width: "100%", padding: "8px 10px", borderRadius: 8, border: "1px solid rgba(0,0,0,0.12)", fontSize: 13, background: "#fff", outline: "none" },
  range: { width: "100%", accentColor: "#7c6aff" },
  colorInput: { width: 36, height: 36, padding: 0, border: "2px solid rgba(0,0,0,0.1)", borderRadius: 8, cursor: "pointer", background: "none" },
  saveArea: { marginTop: "auto", padding: "16px 18px", display: "flex", flexDirection: "column", gap: 8 },
  saveBtn: { width: "100%", padding: "12px 0", border: "none", borderRadius: 10, color: "#fff", fontSize: 14, fontWeight: 700, cursor: "pointer", transition: "opacity 0.15s" },
  layerBtn: { background: "none", border: "1px solid rgba(0,0,0,0.1)", borderRadius: 4, padding: "2px 4px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" },
};
